name: Deploy to AWS Elastic Beanstalk

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:16-alpine

                env:
                    POSTGRES_USER: ${{ secrets.DB_USERNAME }}
                    POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
                    POSTGRES_DB: ${{ secrets.DB_DATABASE }}
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '22'

            - name: Create Env File
              env:
                  ENV: ${{ secrets.ENV }}
                  DB_TYPE: ${{ secrets.DB_TYPE }}
                  DB_HOST: ${{ secrets.DB_HOST }}
                  DB_PORT: ${{ secrets.DB_PORT }}
                  DB_USERNAME: ${{ secrets.DB_USERNAME }}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                  DB_DATABASE: ${{ secrets.DB_DATABASE }}
                  SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
                  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
                  REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
              run: env | grep -E '^(ENV|DB_|SALT_|ACCESS_|REFRESH_)=' > .env

            - name: Create Folders
              run: |
                  mkdir -p ./public/movie
                  mkdir -p ./public/temp

            - name: Install dependencies
              run: npm install --legacy-peer-deps

            - name: Build Project
              run: npm run build

            - name: Install TypeORM
              run: npm install -g typeorm

            - name: Run Migration
              run: npm run typeorm migration:run -d ./dist/database/data-source.js

            - name: Zip Artifact For Deplyment
              run: zip -r deployment.zip .

            - name: Upload To S3
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
                  S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
              run: |
                  aws s3 cp deployment.zip "s3://${S3_BUCKET}/deployment.zip"

            - name: Deploy to AWS Elastic Beanstalk
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
                  S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
              run: |
                  aws elasticbeanstalk create-application-version \
                    --application-name NestJS-Project-EB \
                    --version-label "$GITHUB_SHA" \
                    --source-bundle "S3Bucket=${S3_BUCKET},S3Key=deployment.zip"

                  aws elasticbeanstalk update-environment \
                    --application-name NestJS-Project-EB \
                    --environment-name NestJS-Project-EB-env \
                    --version-label "$GITHUB_SHA"
